<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.72.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Targets.Sdk\Targets.Sdk.csproj" />
  </ItemGroup>

</Project>
